POST http://localhost:9090/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="%HOMEPATH%\\Downloads\\Compressed\\cmder_mini.zip"

< ./%HOMEPATH%/Downloads/Compressed/cmder_mini.zip
--WebAppBoundary--

###
